name: CMake-Hunter-Boost

on: [push, pull_request]

env:
  BUILD_TYPE: Release

  CMAKE_EXECUTE_PROCESS_COMMAND_ECHO: STDOUT

jobs:
  build:
    name: Windows Latest MSVC
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.7z",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      shell: cmake -P {0}
      run: |
        # set(ENV{CC} cl)
        # set(ENV{CXX} cl)

        execute_process(
          COMMAND_ERROR_IS_FATAL ANY
          COMMAND "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && set
          OUTPUT_FILE environment_script_output.txt
        )

        file(STRINGS environment_script_output.txt output_lines)
        foreach(line IN LISTS output_lines)
          if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
            set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
            message(STATUS "ENV: ${CMAKE_MATCH_1} = ${CMAKE_MATCH_2}")
          endif()
        endforeach()

        execute_process(
          COMMAND cmake
            -S .
            -B $ENV{RUNNER_TEMP}/build
            -G "Visual Studio 17 2022"
            -A x64
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
