name: CMake-Hunter-Boost

on: [push, pull_request]

jobs:
  build:
    name: Windows Latest MSVC
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSVC environment
      shell: cmd
      run: |
        echo =================================
        echo === Environment BEFORE MSVC:
        echo =================================
        set
        echo =================================
        call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        set >> "%GITHUB_ENV%"
        echo =================================
        echo === Environment AFTER MSVC:
        echo =================================
        set
        echo =================================

    - name: Configure
      shell: bash
      run: |
        set -e
        echo =================================
        env | sort
        echo =================================
        set -x

        cmake \
            -S . \
            -B $RUNNER_TEMP/build \
            -G "Visual Studio 17 2022" \
            -A x64
